### ISSUE TITLE
Add new event: Automatic end date adjustment

### ISSUE THREAD

**Issue by timstampfli** [tinuwalther/RotaMaster#35]
When I add a new event in the calendar, I select a start date (e.g. 2nd february 2025) and then the end date is still todays date (e.g. 3rd december 2024). I would like to have an automatic adjustment of the end date at least to the time point "start date". This would help reduce scrolling through calendar.

**Comment by tinuwalther** [comment]
Create a Listener for id "start".
Create a function for:
- if selected start and end is null or less than start, then set end to now

**Comment by tinuwalther** [comment]
Implemented in Version 5.3.6
